language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package publishOnlyWhenOnMaster
scala:
  - 2.11.0-RC3
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
    - denys.shabalin@typesafe.com
    - vladimir.nikolaev9@gmail.com
env:
  global:
   - SCALAREFLECT_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAREFLECT_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "GvbGFdxWeP78KWqcbvTcsCzIBoaPqrg0dL38R8FhxM9u+tSmdYFxDlabkrXoe9SBEAZ3UXYLh4Ss5vINpkKQM5lrEh0gM4hO0xvWQWGpwzHWyajXDiXG4RcQc+nRCT6lddmAb/av+aETQBFOHVaZzbpbh0ktq75NYonW6Y0Ajro="
   - secure: "Axjp/ialA/fCom6M6Rb8dhSVSj1e7bgKbC2zOli8X+MIKrDBA15eoKG0FE8Y6vO1Pfxxqzc0OtZaJ1pkuS0Q6UvIweQB5Qv6FPSnHgaqUtEfMvAYHiqd5/BzVLAVPKqXNqnP3h8A1nshYVGnRcvwnyysPmkSvZlyPrjYtAMRICI="
